name: Ultimate Live CI/CD Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ultimate-runner:
    runs-on: [self-hosted, windows]
    timeout-minutes: 43200  # 30 يوم
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Working Directory to Runner Path
        shell: powershell
        run: |
          Set-Location "C:\actions-runner\_work"
          Write-Host "Current path: $(Get-Location)"

      - name: Install Chocolatey (if missing)
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }

      - name: Install Tools (Node.js, Python, .NET, FFmpeg)
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          $pkgs = @('nodejs-lts','python','dotnet','ffmpeg')
          foreach ($p in $pkgs) {
            if (-not (choco list --local-only | Select-String $p)) { choco install $p -y --no-progress }
          }
          $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User')

      - name: Detect Projects & Install Dependencies
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          if (Test-Path "package.json") {
              Write-Host "Node.js project detected."
              npm install
          }
          if (Test-Path "requirements.txt") {
              Write-Host "Python project detected."
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt
          }
          if (Get-ChildItem *.csproj -ErrorAction SilentlyContinue) {
              Write-Host ".NET project detected."
              dotnet restore
          }

      - name: Run Tests
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          if (Test-Path "package.json") { npm test || exit 1 }
          if (Test-Path "requirements.txt") { python -m unittest discover || exit 1 }
          if (Get-ChildItem *.csproj -ErrorAction SilentlyContinue) { dotnet test || exit 1 }

      - name: Build / Package
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          if (Test-Path "package.json") { npm run build || exit 1 }
          if (Get-ChildItem *.csproj -ErrorAction SilentlyContinue) { dotnet build || exit 1 }

      - name: Deploy Automatically
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          Write-Host "Deploy commands go here. ضع أي أوامر نشر تلقائي لكل مشروع."

      - name: Show Runner Info
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          Write-Host "Runner Computer: $env:COMPUTERNAME"
          Write-Host "Runner User: Ghassan"
          Write-Host "Projects detected automatically, Build/Test/Deploy completed."

      - name: Live Mode — Keep Runner Active
        if: ${{ github.event.inputs.keep_live == 'true' || github.event_name == 'workflow_dispatch' }}
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          Write-Host "`n=== ULTIMATE LIVE MODE ACTIVE ==="
          while ($true) {
              Write-Host "[$(Get-Date)] Runner Ghassan active and ready for any new Workflow"
              Start-Sleep -Seconds 300
          }
